### ISSUE TITLE
broken in mickledore

### ISSUE THREAD

**Issue by coreycothrum** [coreycothrum/meta-bitbake-variable-substitution#2]
when building w/ mickledore, this layer is not working. The variables are not replaced.

**Comment by coreycothrum** [comment]
@skinny says `${D}` is no longer correct when building up the search/sub paths. I concur

It seems `${WORKDIR}` is set to `/`. I don't see anything about this in YOCTO migration notes notes

**Comment by coreycothrum** [comment]
Seems `WORKDIR` is being set to `/` in [BB_HASH_CODEPARSER_VALS](https://docs.yoctoproject.org/bitbake/2.6/bitbake-user-manual/bitbake-user-manual-ref-variables.html#term-BB_HASH_CODEPARSER_VALS).

**Comment by coreycothrum** [comment]
Think I have a fix, testing....

**Comment by skinny** [comment]
confirmed to be working (again), thanks for the fix and updating the layer compatibility!
